export type TechnologyCatalogItem = {
  name: string;
  category:
    | 'Frontend'
    | 'Backend'
    | 'Mobile'
    | 'Banco de Dados'
    | 'DevOps/Cloud'
    | 'Design/Produto'
    | 'Outros';
};

export const TECHNOLOGY_CATALOG: TechnologyCatalogItem[] = [
  { name: 'React', category: 'Frontend' },
  { name: 'Next.js', category: 'Frontend' },
  { name: 'Vue', category: 'Frontend' },
  { name: 'Angular', category: 'Frontend' },
  { name: 'Svelte', category: 'Frontend' },
  { name: 'Astro', category: 'Frontend' },
  { name: 'Remix', category: 'Frontend' },
  { name: 'HTML', category: 'Frontend' },
  { name: 'CSS', category: 'Frontend' },
  { name: 'Sass', category: 'Frontend' },
  { name: 'Tailwind CSS', category: 'Frontend' },
  { name: 'Bootstrap', category: 'Frontend' },
  { name: 'JavaScript', category: 'Frontend' },
  { name: 'TypeScript', category: 'Frontend' },
  { name: 'Redux', category: 'Frontend' },
  { name: 'Three.js', category: 'Frontend' },

  { name: 'Node.js', category: 'Backend' },
  { name: 'Express', category: 'Backend' },
  { name: 'NestJS', category: 'Backend' },
  { name: 'Java', category: 'Backend' },
  { name: 'Spring Boot', category: 'Backend' },
  { name: 'PHP', category: 'Backend' },
  { name: 'Laravel', category: 'Backend' },
  { name: 'Python', category: 'Backend' },
  { name: 'Django', category: 'Backend' },
  { name: 'Flask', category: 'Backend' },
  { name: 'FastAPI', category: 'Backend' },
  { name: 'C#', category: 'Backend' },
  { name: '.NET', category: 'Backend' },
  { name: 'Go', category: 'Backend' },
  { name: 'Rust', category: 'Backend' },
  { name: 'Ruby', category: 'Backend' },
  { name: 'Ruby on Rails', category: 'Backend' },
  { name: 'Elixir', category: 'Backend' },

  { name: 'React Native', category: 'Mobile' },
  { name: 'Flutter', category: 'Mobile' },
  { name: 'Kotlin', category: 'Mobile' },
  { name: 'Swift', category: 'Mobile' },
  { name: 'SwiftUI', category: 'Mobile' },
  { name: 'Jetpack Compose', category: 'Mobile' },
  { name: 'Ionic', category: 'Mobile' },

  { name: 'PostgreSQL', category: 'Banco de Dados' },
  { name: 'MySQL', category: 'Banco de Dados' },
  { name: 'MariaDB', category: 'Banco de Dados' },
  { name: 'SQL Server', category: 'Banco de Dados' },
  { name: 'Oracle', category: 'Banco de Dados' },
  { name: 'MongoDB', category: 'Banco de Dados' },
  { name: 'SQLite', category: 'Banco de Dados' },
  { name: 'Redis', category: 'Banco de Dados' },
  { name: 'Firebase', category: 'Banco de Dados' },
  { name: 'Supabase', category: 'Banco de Dados' },
  { name: 'Elasticsearch', category: 'Banco de Dados' },

  { name: 'Docker', category: 'DevOps/Cloud' },
  { name: 'Kubernetes', category: 'DevOps/Cloud' },
  { name: 'AWS', category: 'DevOps/Cloud' },
  { name: 'Azure', category: 'DevOps/Cloud' },
  { name: 'Google Cloud', category: 'DevOps/Cloud' },
  { name: 'Terraform', category: 'DevOps/Cloud' },
  { name: 'GitHub Actions', category: 'DevOps/Cloud' },
  { name: 'GitLab CI', category: 'DevOps/Cloud' },
  { name: 'Jenkins', category: 'DevOps/Cloud' },
  { name: 'Vercel', category: 'DevOps/Cloud' },
  { name: 'Netlify', category: 'DevOps/Cloud' },
  { name: 'Cloudflare', category: 'DevOps/Cloud' },
  { name: 'Linux', category: 'DevOps/Cloud' },
  { name: 'Nginx', category: 'DevOps/Cloud' },

  { name: 'Figma', category: 'Design/Produto' },
  { name: 'UI/UX', category: 'Design/Produto' },
  { name: 'Design Systems', category: 'Design/Produto' },
  { name: 'Prototipagem', category: 'Design/Produto' },
  { name: 'Adobe XD', category: 'Design/Produto' },
  { name: 'Sketch', category: 'Design/Produto' },
  { name: 'Framer', category: 'Design/Produto' },
  { name: 'Photoshop', category: 'Design/Produto' },
  { name: 'Illustrator', category: 'Design/Produto' },
  { name: 'InDesign', category: 'Design/Produto' },
  { name: 'Lightroom', category: 'Design/Produto' },
  { name: 'After Effects', category: 'Design/Produto' },
  { name: 'Premiere Pro', category: 'Design/Produto' },
  { name: 'CorelDRAW', category: 'Design/Produto' },
  { name: 'Canva', category: 'Design/Produto' },
  { name: 'Procreate', category: 'Design/Produto' },
  { name: 'Blender', category: 'Design/Produto' },
  { name: 'Cinema 4D', category: 'Design/Produto' },
  { name: 'Maya', category: 'Design/Produto' },
  { name: 'ZBrush', category: 'Design/Produto' },
  { name: 'Spline', category: 'Design/Produto' },
  { name: 'Motion Design', category: 'Design/Produto' },

  { name: 'Git', category: 'Outros' },
  { name: 'APIs REST', category: 'Outros' },
  { name: 'GraphQL', category: 'Outros' },
  { name: 'Testes', category: 'Outros' },
  { name: 'Cypress', category: 'Outros' },
  { name: 'Jest', category: 'Outros' },
  { name: 'Playwright', category: 'Outros' },
  { name: 'Selenium', category: 'Outros' },
  { name: 'Postman', category: 'Outros' },
  { name: 'Scrum', category: 'Outros' },
  { name: 'Kanban', category: 'Outros' },
  { name: 'WordPress', category: 'Outros' },
  { name: 'SEO', category: 'Outros' },
  { name: 'Power BI', category: 'Outros' },
  { name: 'Machine Learning', category: 'Outros' },
  { name: 'TensorFlow', category: 'Outros' },
  { name: 'Pandas', category: 'Outros' },
];

export function normalizeTechnologyName(name: string): string {
  return name.trim().toLowerCase();
}
